media:
  input: public
  output: /
components:
  seo:
    type: object
    label: SEO
    fields:
      - name: focus_keyword
        label: Focus Keyword
        type: string
      - name: seo_title
        label: SEO Title
        type: string
      - name: seo_description
        label: SEO Description
        type: text
      - name: canonical_url
        label: Canonical URL
        type: string
      - name: og_image
        label: Social Preview Image Override
        type: image
      - name: og_image_alt
        label: Social Preview Image Alt
        type: string
      - name: seo_body
        label: "Body"
        type: rich-text
        options: {
          input: src/assets/seo,
          output: /assets/seo
        }
      - { name: noindex, label: Noindex, type: boolean, default: false }
content:
  - name: posts
    label: Posts
    type: collection
    path: src/content/posts
    view:
      fields: [ title, draft, date ]
    filename: "{year}-{month}-{day}-{fields.slug}.md"
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name : section, label: Section, type: string, required: true }
      - { name: description, label: Description, type: string }
      - { name: "date", label: "Date", type: "date" }
      - { name: "previewImage", label: "Preview Image", type: "image", required: false }
      - { name: body, label: Body, type: rich-text,
          options: { 
            input: src/assets/posts,
            output: /assets/posts
          } 
        }
      - { name: seo, component: seo, label: SEO Meta Data }
  - name: pages
    label: Pages
    type: collection
    path: src/content/pages
    view:
      fields: [ title, draft, date ]
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name : section, label: Section, type: string, required: true }
      - { name: description, label: Description, type: string }
      - { name: "date", label: "Date", type: "date" }
      - { name: "previewImage", label: "Preview Image", type: "image", required: false }
      - { name: body, label: Body, type: rich-text, 
          options: { 
            input: src/assets/pages,
            output: /assets/pages
          } 
        }
      - { name: seo, component: seo, label: SEO Meta Data }